package com.score.backend.exceptions;

public enum ExceptionType {
    DUPLICATE_NICKNAME,
    FULL_GROUP,
    ALREADY_JOINED_GROUP,
    ALREADY_FRIEND,
    ALREADY_BLOCKED,
    TOO_FREQUENT_SCHOOL_CHANGING,
    UNSUPPORTED_FILE_TYPE,
    EXCEEDED_FILE_SIZE,
    INPUT_FORMAT_ERROR,
    GROUP_ADMIN_WITHDRAWAL
}
